apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-db-secret
  namespace: catalog
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name:           catalog-db-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key:      /bookstore/catalog-db-credentials
        property: DB_USERNAME

    - secretKey: DB_PASSWORD
      remoteRef:
        key:      /bookstore/catalog-db-credentials
        property: DB_PASSWORD

    - secretKey: DB_HOST
      remoteRef:
        key:      /bookstore/catalog-db-credentials
        property: DB_HOST
