apiVersion: v1
kind: Namespace
metadata:
  name: catalog
  labels:
    name: catalog
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
