apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: bookstore-api-gateway
  newName: 000000000000.dkr.ecr.us-west-1.amazonaws.com/bookstore-api-gateway
  newTag: latest
