apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstore

resources:
- storageclass/gp3.yaml
- namespace.yaml
- cert-manager/cluster-issuer.yaml
- configmaps/backend-config.yaml
- secrets/external-secret.yaml
- backend/rollout.yaml
- backend/service.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- ingress/ingress.yaml
- network-policy/network-policy.yaml
- pdb/pdb.yaml
- monitoring/servicemonitor.yaml
- monitoring/prometheus-rules.yaml
- monitoring/analysis-template.yaml
