apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: order-db-secret
  namespace: order
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name:           order-db-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key:      /bookstore/order-db-credentials
        property: DB_USERNAME

    - secretKey: DB_PASSWORD
      remoteRef:
        key:      /bookstore/order-db-credentials
        property: DB_PASSWORD

    - secretKey: DB_HOST
      remoteRef:
        key:      /bookstore/order-db-credentials
        property: DB_HOST
